language: ruby
rvm:
  - 2.1.0
branches:
  only:
    - master
script: rake travis
env:
  global:
    - secure: YS4iu8XZ3Akk7luM6FrUUx8sHhnKm4CMec4bQV7JOUhDOEiqPdiO00tVzuSMI6QQJTuaZn/mWZmO6iVbZUUAXCH61kVonHJAPhN9fz06R7FuSYTJhYhA00JR48V74AtfDNIkcjowk0e/nZV8JiLn1P4TTIsYM3sLfV8NZ6hEXxs=
